const flightListData = {
  data: {
    context: {
      status: "incomplete",
      sessionId:
        "ClQIARJQCk4KJDgzOWY0Y2NmLTdmNzgtNDgyMi05YjUzLWJiYzYzNDk1NzhjZBACGiRmMWQ3NjYxZi0xNGYxLTQ5MWUtYTZmOS00OGU0NGI4ZjRhYTESKHVzc18xZmI4MjhhMC1iODExLTQ4OWQtOTM3My1kMmI1MGFmMjdmYjA=",
      totalResults: 10,
    },
    itineraries: [
      {
        id: "9436-2407180830--31435-0-10075-2407180955",
        price: {
          raw: 2046.69,
          formatted: "₹ 2,047",
          pricingOptionId: "za53Oh1Pnw6G",
        },
        legs: [
          {
            id: "9436-2407180830--31435-0-10075-2407180955",
            origin: {
              id: "PNQ",
              entityId: "95673366",
              name: "Pune",
              displayCode: "PNQ",
              city: "Pune",
              country: "India",
              isHighlighted: false,
            },
            destination: {
              id: "BOM",
              entityId: "95673320",
              name: "Mumbai",
              displayCode: "BOM",
              city: "Mumbai",
              country: "India",
              isHighlighted: false,
            },
            durationInMinutes: 85,
            stopCount: 0,
            isSmallestStops: false,
            departure: "2024-07-18T08:30:00",
            arrival: "2024-07-18T09:55:00",
            timeDeltaInDays: 0,
            carriers: {
              marketing: [
                {
                  id: -31435,
                  logoUrl:
                    "https://logos.skyscnr.com/images/airlines/favicon/IK.png",
                  name: "Vistara",
                },
              ],
              operationType: "fully_operated",
            },
            segments: [
              {
                id: "9436-10075-2407180830-2407180955--31435",
                origin: {
                  flightPlaceId: "AMD",
                  displayCode: "AMD",
                  parent: {
                    flightPlaceId: "IAMD",
                    displayCode: "AMD",
                    name: "Ahmedabad",
                    type: "City",
                  },
                  name: "Ahmedabad",
                  type: "Airport",
                  country: "India",
                },
                destination: {
                  flightPlaceId: "BOM",
                  displayCode: "BOM",
                  parent: {
                    flightPlaceId: "IBOM",
                    displayCode: "BOM",
                    name: "Mumbai",
                    type: "City",
                  },
                  name: "Mumbai",
                  type: "Airport",
                  country: "India",
                },
                departure: "2024-07-18T08:30:00",
                arrival: "2024-07-18T09:55:00",
                durationInMinutes: 85,
                flightNumber: "936",
                marketingCarrier: {
                  id: -31435,
                  name: "Vistara",
                  alternateId: "IK",
                  allianceId: 0,
                  displayCode: "",
                },
                operatingCarrier: {
                  id: -31435,
                  name: "Vistara",
                  alternateId: "IK",
                  allianceId: 0,
                  displayCode: "",
                },
              },
            ],
          },
        ],
        isSelfTransfer: false,
        isProtectedSelfTransfer: false,
        farePolicy: {
          isChangeAllowed: false,
          isPartiallyChangeable: false,
          isCancellationAllowed: false,
          isPartiallyRefundable: false,
        },
        fareAttributes: {},
        tags: ["third_cheapest"],
        isMashUp: false,
        hasFlexibleOptions: false,
        score: 0.999,
      },
      {
        id: "9436-2407181930--32213-0-10075-2407182050",
        price: {
          raw: 2200.0,
          formatted: "₹ 2,200",
          pricingOptionId: "HGyimGMJ8npC",
        },
        legs: [
          {
            id: "9436-2407181930--32213-0-10075-2407182050",
            origin: {
              id: "AMD",
              entityId: "95673366",
              name: "Ahmedabad",
              displayCode: "AMD",
              city: "Ahmedabad",
              country: "India",
              isHighlighted: false,
            },
            destination: {
              id: "BOM",
              entityId: "95673320",
              name: "Mumbai",
              displayCode: "BOM",
              city: "Mumbai",
              country: "India",
              isHighlighted: false,
            },
            durationInMinutes: 80,
            stopCount: 0,
            isSmallestStops: false,
            departure: "2024-07-18T19:30:00",
            arrival: "2024-07-18T20:50:00",
            timeDeltaInDays: 0,
            carriers: {
              marketing: [
                {
                  id: -32213,
                  logoUrl:
                    "https://logos.skyscnr.com/images/airlines/favicon/49.png",
                  name: "IndiGo",
                },
              ],
              operationType: "fully_operated",
            },
            segments: [
              {
                id: "9436-10075-2407181930-2407182050--32213",
                origin: {
                  flightPlaceId: "AMD",
                  displayCode: "AMD",
                  parent: {
                    flightPlaceId: "IAMD",
                    displayCode: "AMD",
                    name: "Ahmedabad",
                    type: "City",
                  },
                  name: "Ahmedabad",
                  type: "Airport",
                  country: "India",
                },
                destination: {
                  flightPlaceId: "BOM",
                  displayCode: "BOM",
                  parent: {
                    flightPlaceId: "IBOM",
                    displayCode: "BOM",
                    name: "Mumbai",
                    type: "City",
                  },
                  name: "Mumbai",
                  type: "Airport",
                  country: "India",
                },
                departure: "2024-07-18T19:30:00",
                arrival: "2024-07-18T20:50:00",
                durationInMinutes: 80,
                flightNumber: "649",
                marketingCarrier: {
                  id: -32213,
                  name: "IndiGo",
                  alternateId: "49",
                  allianceId: 0,
                  displayCode: "",
                },
                operatingCarrier: {
                  id: -32213,
                  name: "IndiGo",
                  alternateId: "49",
                  allianceId: 0,
                  displayCode: "",
                },
              },
            ],
          },
        ],
        isSelfTransfer: false,
        isProtectedSelfTransfer: false,
        farePolicy: {
          isChangeAllowed: false,
          isPartiallyChangeable: false,
          isCancellationAllowed: false,
          isPartiallyRefundable: false,
        },
        fareAttributes: {},
        isMashUp: false,
        hasFlexibleOptions: false,
        score: 0.892932,
      },
      {
        id: "9436-2407180450--31435-0-10075-2407180615",
        price: {
          raw: 2046.69,
          formatted: "₹ 2,047",
          pricingOptionId: "6xn-cSnDMMY5",
        },
        legs: [
          {
            id: "9436-2407180450--31435-0-10075-2407180615",
            origin: {
              id: "AMD",
              entityId: "95673366",
              name: "Ahmedabad",
              displayCode: "AMD",
              city: "Ahmedabad",
              country: "India",
              isHighlighted: false,
            },
            destination: {
              id: "BOM",
              entityId: "95673320",
              name: "Mumbai",
              displayCode: "BOM",
              city: "Mumbai",
              country: "India",
              isHighlighted: false,
            },
            durationInMinutes: 85,
            stopCount: 0,
            isSmallestStops: false,
            departure: "2024-07-18T04:50:00",
            arrival: "2024-07-18T06:15:00",
            timeDeltaInDays: 0,
            carriers: {
              marketing: [
                {
                  id: -31435,
                  logoUrl:
                    "https://logos.skyscnr.com/images/airlines/favicon/IK.png",
                  name: "Vistara",
                },
              ],
              operationType: "fully_operated",
            },
            segments: [
              {
                id: "9436-10075-2407180450-2407180615--31435",
                origin: {
                  flightPlaceId: "AMD",
                  displayCode: "AMD",
                  parent: {
                    flightPlaceId: "IAMD",
                    displayCode: "AMD",
                    name: "Ahmedabad",
                    type: "City",
                  },
                  name: "Ahmedabad",
                  type: "Airport",
                  country: "India",
                },
                destination: {
                  flightPlaceId: "BOM",
                  displayCode: "BOM",
                  parent: {
                    flightPlaceId: "IBOM",
                    displayCode: "BOM",
                    name: "Mumbai",
                    type: "City",
                  },
                  name: "Mumbai",
                  type: "Airport",
                  country: "India",
                },
                departure: "2024-07-18T04:50:00",
                arrival: "2024-07-18T06:15:00",
                durationInMinutes: 85,
                flightNumber: "918",
                marketingCarrier: {
                  id: -31435,
                  name: "Vistara",
                  alternateId: "IK",
                  allianceId: 0,
                  displayCode: "",
                },
                operatingCarrier: {
                  id: -31435,
                  name: "Vistara",
                  alternateId: "IK",
                  allianceId: 0,
                  displayCode: "",
                },
              },
            ],
          },
        ],
        isSelfTransfer: false,
        isProtectedSelfTransfer: false,
        farePolicy: {
          isChangeAllowed: false,
          isPartiallyChangeable: false,
          isCancellationAllowed: false,
          isPartiallyRefundable: false,
        },
        fareAttributes: {},
        tags: ["third_cheapest"],
        isMashUp: false,
        hasFlexibleOptions: false,
        score: 0.860402,
      },
      {
        id: "9436-2407180015--32213-0-10075-2407180135",
        price: {
          raw: 1989.93,
          formatted: "₹ 1,990",
          pricingOptionId: "LUEfZSfta1C7",
        },
        legs: [
          {
            id: "9436-2407180015--32213-0-10075-2407180135",
            origin: {
              id: "AMD",
              entityId: "95673366",
              name: "Ahmedabad",
              displayCode: "AMD",
              city: "Ahmedabad",
              country: "India",
              isHighlighted: false,
            },
            destination: {
              id: "BOM",
              entityId: "95673320",
              name: "Mumbai",
              displayCode: "BOM",
              city: "Mumbai",
              country: "India",
              isHighlighted: false,
            },
            durationInMinutes: 80,
            stopCount: 0,
            isSmallestStops: false,
            departure: "2024-07-18T00:15:00",
            arrival: "2024-07-18T01:35:00",
            timeDeltaInDays: 0,
            carriers: {
              marketing: [
                {
                  id: -32213,
                  logoUrl:
                    "https://logos.skyscnr.com/images/airlines/favicon/49.png",
                  name: "IndiGo",
                },
              ],
              operationType: "fully_operated",
            },
            segments: [
              {
                id: "9436-10075-2407180015-2407180135--32213",
                origin: {
                  flightPlaceId: "AMD",
                  displayCode: "AMD",
                  parent: {
                    flightPlaceId: "IAMD",
                    displayCode: "AMD",
                    name: "Ahmedabad",
                    type: "City",
                  },
                  name: "Ahmedabad",
                  type: "Airport",
                  country: "India",
                },
                destination: {
                  flightPlaceId: "BOM",
                  displayCode: "BOM",
                  parent: {
                    flightPlaceId: "IBOM",
                    displayCode: "BOM",
                    name: "Mumbai",
                    type: "City",
                  },
                  name: "Mumbai",
                  type: "Airport",
                  country: "India",
                },
                departure: "2024-07-18T00:15:00",
                arrival: "2024-07-18T01:35:00",
                durationInMinutes: 80,
                flightNumber: "5272",
                marketingCarrier: {
                  id: -32213,
                  name: "IndiGo",
                  alternateId: "49",
                  allianceId: 0,
                  displayCode: "",
                },
                operatingCarrier: {
                  id: -32213,
                  name: "IndiGo",
                  alternateId: "49",
                  allianceId: 0,
                  displayCode: "",
                },
              },
            ],
          },
        ],
        isSelfTransfer: false,
        isProtectedSelfTransfer: false,
        farePolicy: {
          isChangeAllowed: false,
          isPartiallyChangeable: false,
          isCancellationAllowed: false,
          isPartiallyRefundable: false,
        },
        fareAttributes: {},
        tags: ["second_cheapest", "third_shortest"],
        isMashUp: false,
        hasFlexibleOptions: false,
        score: 0.850235,
      },
      {
        id: "9436-2407181045--32213-0-10075-2407181155",
        price: {
          raw: 2200.0,
          formatted: "₹ 2,200",
          pricingOptionId: "XTgSmwn6DI0k",
        },
        legs: [
          {
            id: "9436-2407181045--32213-0-10075-2407181155",
            origin: {
              id: "AMD",
              entityId: "95673366",
              name: "Ahmedabad",
              displayCode: "AMD",
              city: "Ahmedabad",
              country: "India",
              isHighlighted: false,
            },
            destination: {
              id: "BOM",
              entityId: "95673320",
              name: "Mumbai",
              displayCode: "BOM",
              city: "Mumbai",
              country: "India",
              isHighlighted: false,
            },
            durationInMinutes: 70,
            stopCount: 0,
            isSmallestStops: false,
            departure: "2024-07-18T10:45:00",
            arrival: "2024-07-18T11:55:00",
            timeDeltaInDays: 0,
            carriers: {
              marketing: [
                {
                  id: -32213,
                  logoUrl:
                    "https://logos.skyscnr.com/images/airlines/favicon/49.png",
                  name: "IndiGo",
                },
              ],
              operationType: "fully_operated",
            },
            segments: [
              {
                id: "9436-10075-2407181045-2407181155--32213",
                origin: {
                  flightPlaceId: "AMD",
                  displayCode: "AMD",
                  parent: {
                    flightPlaceId: "IAMD",
                    displayCode: "AMD",
                    name: "Ahmedabad",
                    type: "City",
                  },
                  name: "Ahmedabad",
                  type: "Airport",
                  country: "India",
                },
                destination: {
                  flightPlaceId: "BOM",
                  displayCode: "BOM",
                  parent: {
                    flightPlaceId: "IBOM",
                    displayCode: "BOM",
                    name: "Mumbai",
                    type: "City",
                  },
                  name: "Mumbai",
                  type: "Airport",
                  country: "India",
                },
                departure: "2024-07-18T10:45:00",
                arrival: "2024-07-18T11:55:00",
                durationInMinutes: 70,
                flightNumber: "533",
                marketingCarrier: {
                  id: -32213,
                  name: "IndiGo",
                  alternateId: "49",
                  allianceId: 0,
                  displayCode: "",
                },
                operatingCarrier: {
                  id: -32213,
                  name: "IndiGo",
                  alternateId: "49",
                  allianceId: 0,
                  displayCode: "",
                },
              },
            ],
          },
        ],
        isSelfTransfer: false,
        isProtectedSelfTransfer: false,
        farePolicy: {
          isChangeAllowed: false,
          isPartiallyChangeable: false,
          isCancellationAllowed: false,
          isPartiallyRefundable: false,
        },
        fareAttributes: {},
        tags: ["second_shortest"],
        isMashUp: false,
        hasFlexibleOptions: false,
        score: 0.844403,
      },
      {
        id: "9436-2407181815--32213-0-10075-2407181940",
        price: {
          raw: 2334.66,
          formatted: "₹ 2,335",
          pricingOptionId: "gzHg3Z3SZEM2",
        },
        legs: [
          {
            id: "9436-2407181815--32213-0-10075-2407181940",
            origin: {
              id: "AMD",
              entityId: "95673366",
              name: "Ahmedabad",
              displayCode: "AMD",
              city: "Ahmedabad",
              country: "India",
              isHighlighted: false,
            },
            destination: {
              id: "BOM",
              entityId: "95673320",
              name: "Mumbai",
              displayCode: "BOM",
              city: "Mumbai",
              country: "India",
              isHighlighted: false,
            },
            durationInMinutes: 85,
            stopCount: 0,
            isSmallestStops: false,
            departure: "2024-07-18T18:15:00",
            arrival: "2024-07-18T19:40:00",
            timeDeltaInDays: 0,
            carriers: {
              marketing: [
                {
                  id: -32213,
                  logoUrl:
                    "https://logos.skyscnr.com/images/airlines/favicon/49.png",
                  name: "IndiGo",
                },
              ],
              operationType: "fully_operated",
            },
            segments: [
              {
                id: "9436-10075-2407181815-2407181940--32213",
                origin: {
                  flightPlaceId: "AMD",
                  displayCode: "AMD",
                  parent: {
                    flightPlaceId: "IAMD",
                    displayCode: "AMD",
                    name: "Ahmedabad",
                    type: "City",
                  },
                  name: "Ahmedabad",
                  type: "Airport",
                  country: "India",
                },
                destination: {
                  flightPlaceId: "BOM",
                  displayCode: "BOM",
                  parent: {
                    flightPlaceId: "IBOM",
                    displayCode: "BOM",
                    name: "Mumbai",
                    type: "City",
                  },
                  name: "Mumbai",
                  type: "Airport",
                  country: "India",
                },
                departure: "2024-07-18T18:15:00",
                arrival: "2024-07-18T19:40:00",
                durationInMinutes: 85,
                flightNumber: "803",
                marketingCarrier: {
                  id: -32213,
                  name: "IndiGo",
                  alternateId: "49",
                  allianceId: 0,
                  displayCode: "",
                },
                operatingCarrier: {
                  id: -32213,
                  name: "IndiGo",
                  alternateId: "49",
                  allianceId: 0,
                  displayCode: "",
                },
              },
            ],
          },
        ],
        isSelfTransfer: false,
        isProtectedSelfTransfer: false,
        farePolicy: {
          isChangeAllowed: false,
          isPartiallyChangeable: false,
          isCancellationAllowed: false,
          isPartiallyRefundable: false,
        },
        fareAttributes: {},
        isMashUp: false,
        hasFlexibleOptions: false,
        score: 0.800625,
      },
      {
        id: "9436-2407182235--32213-0-10075-2407190005",
        price: {
          raw: 2200.0,
          formatted: "₹ 2,200",
          pricingOptionId: "FkODXbu2YbkY",
        },
        legs: [
          {
            id: "9436-2407182235--32213-0-10075-2407190005",
            origin: {
              id: "AMD",
              entityId: "95673366",
              name: "Ahmedabad",
              displayCode: "AMD",
              city: "Ahmedabad",
              country: "India",
              isHighlighted: false,
            },
            destination: {
              id: "BOM",
              entityId: "95673320",
              name: "Mumbai",
              displayCode: "BOM",
              city: "Mumbai",
              country: "India",
              isHighlighted: false,
            },
            durationInMinutes: 90,
            stopCount: 0,
            isSmallestStops: false,
            departure: "2024-07-18T22:35:00",
            arrival: "2024-07-19T00:05:00",
            timeDeltaInDays: 1,
            carriers: {
              marketing: [
                {
                  id: -32213,
                  logoUrl:
                    "https://logos.skyscnr.com/images/airlines/favicon/49.png",
                  name: "IndiGo",
                },
              ],
              operationType: "fully_operated",
            },
            segments: [
              {
                id: "9436-10075-2407182235-2407190005--32213",
                origin: {
                  flightPlaceId: "AMD",
                  displayCode: "AMD",
                  parent: {
                    flightPlaceId: "IAMD",
                    displayCode: "AMD",
                    name: "Ahmedabad",
                    type: "City",
                  },
                  name: "Ahmedabad",
                  type: "Airport",
                  country: "India",
                },
                destination: {
                  flightPlaceId: "BOM",
                  displayCode: "BOM",
                  parent: {
                    flightPlaceId: "IBOM",
                    displayCode: "BOM",
                    name: "Mumbai",
                    type: "City",
                  },
                  name: "Mumbai",
                  type: "Airport",
                  country: "India",
                },
                departure: "2024-07-18T22:35:00",
                arrival: "2024-07-19T00:05:00",
                durationInMinutes: 90,
                flightNumber: "5148",
                marketingCarrier: {
                  id: -32213,
                  name: "IndiGo",
                  alternateId: "49",
                  allianceId: 0,
                  displayCode: "",
                },
                operatingCarrier: {
                  id: -32213,
                  name: "IndiGo",
                  alternateId: "49",
                  allianceId: 0,
                  displayCode: "",
                },
              },
            ],
          },
        ],
        isSelfTransfer: false,
        isProtectedSelfTransfer: false,
        farePolicy: {
          isChangeAllowed: false,
          isPartiallyChangeable: false,
          isCancellationAllowed: false,
          isPartiallyRefundable: false,
        },
        fareAttributes: {},
        isMashUp: false,
        hasFlexibleOptions: false,
        score: 0.795983,
      },
      {
        id: "9436-2407180415--32213-0-10075-2407180525",
        price: {
          raw: 1989.93,
          formatted: "₹ 1,990",
          pricingOptionId: "H98FAdDLX-jJ",
        },
        legs: [
          {
            id: "9436-2407180415--32213-0-10075-2407180525",
            origin: {
              id: "AMD",
              entityId: "95673366",
              name: "Ahmedabad",
              displayCode: "AMD",
              city: "Ahmedabad",
              country: "India",
              isHighlighted: false,
            },
            destination: {
              id: "BOM",
              entityId: "95673320",
              name: "Mumbai",
              displayCode: "BOM",
              city: "Mumbai",
              country: "India",
              isHighlighted: false,
            },
            durationInMinutes: 70,
            stopCount: 0,
            isSmallestStops: false,
            departure: "2024-07-18T04:15:00",
            arrival: "2024-07-18T05:25:00",
            timeDeltaInDays: 0,
            carriers: {
              marketing: [
                {
                  id: -32213,
                  logoUrl:
                    "https://logos.skyscnr.com/images/airlines/favicon/49.png",
                  name: "IndiGo",
                },
              ],
              operationType: "fully_operated",
            },
            segments: [
              {
                id: "9436-10075-2407180415-2407180525--32213",
                origin: {
                  flightPlaceId: "AMD",
                  displayCode: "AMD",
                  parent: {
                    flightPlaceId: "IAMD",
                    displayCode: "AMD",
                    name: "Ahmedabad",
                    type: "City",
                  },
                  name: "Ahmedabad",
                  type: "Airport",
                  country: "India",
                },
                destination: {
                  flightPlaceId: "BOM",
                  displayCode: "BOM",
                  parent: {
                    flightPlaceId: "IBOM",
                    displayCode: "BOM",
                    name: "Mumbai",
                    type: "City",
                  },
                  name: "Mumbai",
                  type: "Airport",
                  country: "India",
                },
                departure: "2024-07-18T04:15:00",
                arrival: "2024-07-18T05:25:00",
                durationInMinutes: 70,
                flightNumber: "5182",
                marketingCarrier: {
                  id: -32213,
                  name: "IndiGo",
                  alternateId: "49",
                  allianceId: 0,
                  displayCode: "",
                },
                operatingCarrier: {
                  id: -32213,
                  name: "IndiGo",
                  alternateId: "49",
                  allianceId: 0,
                  displayCode: "",
                },
              },
            ],
          },
        ],
        isSelfTransfer: false,
        isProtectedSelfTransfer: false,
        farePolicy: {
          isChangeAllowed: false,
          isPartiallyChangeable: false,
          isCancellationAllowed: false,
          isPartiallyRefundable: false,
        },
        fareAttributes: {},
        tags: ["cheapest", "shortest"],
        isMashUp: false,
        hasFlexibleOptions: false,
        score: 0.793295,
      },
      {
        id: "9436-2407180805--32672-0-10075-2407180930",
        price: {
          raw: 2261.0,
          formatted: "₹ 2,261",
          pricingOptionId: "-N0AMhqAOd-7",
        },
        legs: [
          {
            id: "9436-2407180805--32672-0-10075-2407180930",
            origin: {
              id: "AMD",
              entityId: "95673366",
              name: "Ahmedabad",
              displayCode: "AMD",
              city: "Ahmedabad",
              country: "India",
              isHighlighted: false,
            },
            destination: {
              id: "BOM",
              entityId: "95673320",
              name: "Mumbai",
              displayCode: "BOM",
              city: "Mumbai",
              country: "India",
              isHighlighted: false,
            },
            durationInMinutes: 85,
            stopCount: 0,
            isSmallestStops: false,
            departure: "2024-07-18T08:05:00",
            arrival: "2024-07-18T09:30:00",
            timeDeltaInDays: 0,
            carriers: {
              marketing: [
                {
                  id: -32672,
                  logoUrl:
                    "https://logos.skyscnr.com/images/airlines/favicon/AI.png",
                  name: "Air India",
                },
              ],
              operationType: "fully_operated",
            },
            segments: [
              {
                id: "9436-10075-2407180805-2407180930--32672",
                origin: {
                  flightPlaceId: "AMD",
                  displayCode: "AMD",
                  parent: {
                    flightPlaceId: "IAMD",
                    displayCode: "AMD",
                    name: "Ahmedabad",
                    type: "City",
                  },
                  name: "Ahmedabad",
                  type: "Airport",
                  country: "India",
                },
                destination: {
                  flightPlaceId: "BOM",
                  displayCode: "BOM",
                  parent: {
                    flightPlaceId: "IBOM",
                    displayCode: "BOM",
                    name: "Mumbai",
                    type: "City",
                  },
                  name: "Mumbai",
                  type: "Airport",
                  country: "India",
                },
                departure: "2024-07-18T08:05:00",
                arrival: "2024-07-18T09:30:00",
                durationInMinutes: 85,
                flightNumber: "614",
                marketingCarrier: {
                  id: -32672,
                  name: "Air India",
                  alternateId: "AI",
                  allianceId: 0,
                  displayCode: "",
                },
                operatingCarrier: {
                  id: -32672,
                  name: "Air India",
                  alternateId: "AI",
                  allianceId: 0,
                  displayCode: "",
                },
              },
            ],
          },
        ],
        isSelfTransfer: false,
        isProtectedSelfTransfer: false,
        farePolicy: {
          isChangeAllowed: false,
          isPartiallyChangeable: false,
          isCancellationAllowed: false,
          isPartiallyRefundable: false,
        },
        fareAttributes: {},
        isMashUp: false,
        hasFlexibleOptions: false,
        score: 0.792561,
      },
      {
        id: "9436-2407180835--32213-0-10075-2407180945",
        price: {
          raw: 2200.0,
          formatted: "₹ 2,200",
          pricingOptionId: "nm-dOOntBFgI",
        },
        legs: [
          {
            id: "9436-2407180835--32213-0-10075-2407180945",
            origin: {
              id: "AMD",
              entityId: "95673366",
              name: "Ahmedabad",
              displayCode: "AMD",
              city: "Ahmedabad",
              country: "India",
              isHighlighted: false,
            },
            destination: {
              id: "BOM",
              entityId: "95673320",
              name: "Mumbai",
              displayCode: "BOM",
              city: "Mumbai",
              country: "India",
              isHighlighted: false,
            },
            durationInMinutes: 70,
            stopCount: 0,
            isSmallestStops: false,
            departure: "2024-07-18T08:35:00",
            arrival: "2024-07-18T09:45:00",
            timeDeltaInDays: 0,
            carriers: {
              marketing: [
                {
                  id: -32213,
                  logoUrl:
                    "https://logos.skyscnr.com/images/airlines/favicon/49.png",
                  name: "IndiGo",
                },
              ],
              operationType: "fully_operated",
            },
            segments: [
              {
                id: "9436-10075-2407180835-2407180945--32213",
                origin: {
                  flightPlaceId: "AMD",
                  displayCode: "AMD",
                  parent: {
                    flightPlaceId: "IAMD",
                    displayCode: "AMD",
                    name: "Ahmedabad",
                    type: "City",
                  },
                  name: "Ahmedabad",
                  type: "Airport",
                  country: "India",
                },
                destination: {
                  flightPlaceId: "BOM",
                  displayCode: "BOM",
                  parent: {
                    flightPlaceId: "IBOM",
                    displayCode: "BOM",
                    name: "Mumbai",
                    type: "City",
                  },
                  name: "Mumbai",
                  type: "Airport",
                  country: "India",
                },
                departure: "2024-07-18T08:35:00",
                arrival: "2024-07-18T09:45:00",
                durationInMinutes: 70,
                flightNumber: "5125",
                marketingCarrier: {
                  id: -32213,
                  name: "IndiGo",
                  alternateId: "49",
                  allianceId: 0,
                  displayCode: "",
                },
                operatingCarrier: {
                  id: -32213,
                  name: "IndiGo",
                  alternateId: "49",
                  allianceId: 0,
                  displayCode: "",
                },
              },
            ],
          },
        ],
        isSelfTransfer: false,
        isProtectedSelfTransfer: false,
        farePolicy: {
          isChangeAllowed: false,
          isPartiallyChangeable: false,
          isCancellationAllowed: false,
          isPartiallyRefundable: false,
        },
        fareAttributes: {},
        tags: ["second_shortest"],
        isMashUp: false,
        hasFlexibleOptions: false,
        score: 0.781868,
      },
    ],
    messages: [],
    filterStats: {
      duration: {
        min: 70,
        max: 90,
        multiCityMin: 70,
        multiCityMax: 90,
      },
      airports: [
        {
          city: "Ahmedabad",
          airports: [
            {
              id: "AMD",
              entityId: "95673366",
              name: "Ahmedabad",
            },
          ],
        },
        {
          city: "Mumbai",
          airports: [
            {
              id: "BOM",
              entityId: "95673320",
              name: "Mumbai",
            },
          ],
        },
      ],
      carriers: [
        {
          id: -32672,
          logoUrl: "https://logos.skyscnr.com/images/airlines/favicon/AI.png",
          name: "Air India",
        },
        {
          id: -32213,
          logoUrl: "https://logos.skyscnr.com/images/airlines/favicon/49.png",
          name: "IndiGo",
        },
        {
          id: -31435,
          logoUrl: "https://logos.skyscnr.com/images/airlines/favicon/IK.png",
          name: "Vistara",
        },
      ],
      stopPrices: {
        direct: {
          isPresent: true,
          formattedPrice: "₹ 1,990",
        },
        one: {
          isPresent: false,
        },
        twoOrMore: {
          isPresent: false,
        },
      },
    },
    flightsSessionId: "839f4ccf-7f78-4822-9b53-bbc6349578cd",
    destinationImageUrl:
      "https://content.skyscnr.com/m/3719e8f4a5daf43d/original/Flights-Placeholder.jpg",
    token:
      "eyJhIjoxLCJjIjowLCJpIjowLCJjYyI6ImVjb25vbXkiLCJvIjoiQU1EIiwiZCI6IkJPTSIsImQxIjoiMjAyNC0wNy0xOCJ9",
  },
  status: true,
  message: "Successful",
};

export default flightListData;
